server:
  port: 8081

spring:
  datasource:
    druid:
      driver_class_name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.211/acceptance?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: reallove
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 30
      initialSize: 10
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  # mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.repository.entity
  # configLocation: classpath:mybatis-config.xml
  global-config:
      idType: 1
      refresh-mapper: true